### ISSUE TITLE
Complete UML diagram

### ISSUE THREAD

**Issue by 20Mphumzi16** [20Mphumzi16/universitycourse#6]

**Comment by Fluffy-J** [comment]
![universitycourse2](https://github.com/20Mphumzi16/universitycourse/assets/104217528/8d992fbf-8103-4ed3-b608-8c8d1b9d47f4)

**Comment by Fluffy-J** [comment]
UML is completed

**Comment by Fluffy-J** [comment]
![universitycourse2UML](https://github.com/20Mphumzi16/universitycourse/assets/104217528/e58a3e5b-1c6b-4e9f-a75a-127f26353ff1)
